 # NumPy 

In [1]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [5]:
#list
a=[1,2,3,3.5,4,"hello"]
a

[1, 2, 3, 3.5, 4, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', '3.5', '4', 'hello'], dtype='<U32')

In [8]:
i=[[1,2,3,4,5],[4,5,6,7,8]]
i

[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]]

In [9]:
np.array(i)

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

# array generation function

In [12]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [22]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# Random Generation

In [23]:
np.random.rand(5) #normalization

array([0.8190029 , 0.38543234, 0.05975773, 0.91562534, 0.27820668])

In [24]:
np.random.randn(10) #standerisation

array([-0.35021132, -0.05677082, -0.85854942,  0.86406468,  0.25737475,
        0.89462861,  1.89799155,  0.69775643,  0.15414033,  0.68123016])

In [26]:
np.random.randint(1,20,30)

array([12,  7,  6, 18,  9, 18, 10,  6,  2,  8,  2, 16, 13,  9,  2, 14,  1,
        4,  2,  4,  4,  1, 12, 15, 19, 17, 10, 13,  4, 18], dtype=int32)

# arrat attributes

In [29]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int64')

# array method

In [36]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(a.min())

1


In [39]:
print(a.max())

9


In [40]:
print(a.sum())

45


In [42]:
np.sum(a,axis=0)

array([12, 15, 18])

In [43]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [44]:
print(a.min())

1


In [45]:
print(a.std())

2.581988897471611


In [46]:
print(a.argmax())

8


In [47]:
print(arr.argmin())

0


# reshape

In [52]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
a1=a.reshape(2,5)
print(a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [62]:
a=np.random.randint(1,11,6)
print(a)
b=a.reshape(3,2)
print(b)
print(b.argmax())
print(b.argmin())

[3 7 7 8 7 3]
[[3 7]
 [7 8]
 [7 3]]
3
0


# indexing

In [64]:
import numpy as np
a=np.arange(11,21)
print(a)

[11 12 13 14 15 16 17 18 19 20]


In [65]:
print(a[3])

14


In [67]:
print(a[1:5])

[12 13 14 15]


In [68]:
print(a[:5])

[11 12 13 14 15]


In [69]:
print(a[:])

[11 12 13 14 15 16 17 18 19 20]


In [70]:
print(a[0:])

[11 12 13 14 15 16 17 18 19 20]


In [71]:
print(a[1::2])

[12 14 16 18 20]


In [74]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
print(arr[0,0])
print(arr[0:2,1:3])

1


In [77]:
print(arr[0,4])

5


In [78]:
print(arr[5,4])

30


In [83]:
print(arr[3:6,3:5])

[[19 20]
 [24 25]
 [29 30]]


In [85]:
print(arr[5,3:6])

[29 30]


In [86]:
print(arr[:,2])

[ 3  8 13 18 23 28]


In [87]:
arr1=np.arange(11,21)
print(arr1)

[11 12 13 14 15 16 17 18 19 20]


# array operation

In [88]:
a1=np.array([1,2,3,4])
a2=np.array([6,7,8,9])

print(a1+a2)

[ 7  9 11 13]


In [89]:
print(a1-a2)

[-5 -5 -5 -5]


In [90]:
print(a1*a2)

[ 6 14 24 36]


In [92]:
print(a1/a2)

[0.16666667 0.28571429 0.375      0.44444444]


In [93]:
print(a1//a2)

[0 0 0 0]


In [94]:
print(a1 ** a2)

[     1    128   6561 262144]


In [95]:
#broadcasting

In [98]:
t=[10,20,30,40]
p=np.array(t)

In [99]:
print(p+10)

[20 30 40 50]


In [101]:
arr2=np.arange(1,26).reshape(5,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [102]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [103]:
# depp and shallow copy

In [105]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [106]:
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
>>> b = a.copy()
>>> b[2][0] = 10
>>> a

array([1, 'm', list([10, 3, 4])], dtype=object)

In [118]:
a=np.arange(1,21).reshape(2,10)
print(a)
b=a.view()
b[0,0]=7
print(b)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 7  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 7  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [119]:
# matrix operation

In [120]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [121]:
print(a@b)

[[19 22]
 [43 50]]


In [122]:
print(a.T)

[[1 3]
 [2 4]]


In [126]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]


In [128]:
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


In [129]:
print(np.column_stack((a,b)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [130]:
c=np.arange(16).reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [132]:
print(np.hsplit(c,4))

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [134]:
print(np.vsplit(c,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [21]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
print(a)
print(np.split(a,5))
print(a[4:,:])
print(a.size)
print(a.dtype)
b=np.arange(1,26).reshape(5,5)
print(b)
print(a+b)
print(a.T)
print(a.argmax())
print(a.argmin())
print(np.vstack((a,b)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25]])]
[[21 22 23 24 25]]
25
int64
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
24
0
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
s=np.random.randint(1,90,81).reshape(9,9)
print(s)


[[43 15 76 56 22 79 29 62 41]
 [84 67  6 30 24 61 26 58 60]
 [56 33  7 72 15 77 21 32 55]
 [88  8 57 43 86 13 81 10 30]
 [28  4  6 29 65 83 51  3 20]
 [72 36 82 83 52 72  6 35 50]
 [73 74 44 44 25 40 67 28 37]
 [76 88 28 74 83 79 28 41 38]
 [61 34 21 82 87 70 57 79 51]]


In [26]:
data=np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]

])

In [27]:
data.shape

(5, 3)

In [28]:
np.mean(data[:,0])

np.float64(18.4)

In [29]:
print(data[:,1])

[85 92 76 65 90]


In [30]:
np.max(data[:,2])

np.int64(95)

In [32]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [34]:
data[:,1]+5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [35]:
data.ravel()

array([18, 85, 78, 19, 92, 88, 17, 76, 95, 18, 65, 70, 20, 90, 85])

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [4]:
Zeros_arr = np.zeros((3,3))
print(Zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
full_arr=np.full((5,5),7)
print(full_arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [8]:
print(np.dot(a,b))

32


In [10]:
arr=np.arange(1,10).reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr[1, :])

[4 5 6]


In [12]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [13]:
print(a.ravel())

[1 2 3 4 5 6]


In [16]:
a=np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [18]:
a[a%2==0]=-1
a

array([ 1, -1,  3, -1,  5, -1])

In [20]:
arr=np.random.randint(1,10,5)
arr

array([2, 7, 7, 3, 6], dtype=int32)

In [22]:
a=np.array([[1,2] , [3,4]])
b=np.array([[5,6]])
vstack=np.vstack((a,b))
print(vstack)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
hstack=np.hstack((a,b.T))
print(hstack)

[[1 2 5]
 [3 4 6]]


In [25]:
arr=np.arange(9)
print(np.split(arr,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
